import React, { Component, Fragment } from 'react';
import Typography from '@material-ui/core/Typography';
import Paper from '@material-ui/core/Paper';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import ListSubheader from '@material-ui/core/ListSubheader';
import gql from 'graphql-tag';

const fetchMessages = gql`
    subscription {
        Turns {
            hits
            misses
            turnRolls
            username
        }
    }
`
const messages = [
      {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
      },
      {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
          anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
      },
      {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
      },
      {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
      },
      {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
      },
      {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
          navigation drawer or overflow menu) open as bottom sheets at a higher elevation
          than the bar.`,
        person: '/static/images/avatar/5.jpg',
      },
      {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
          for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
      },
  ];

class rollHistory extends Component {
    render() {
        return (
        
        <Paper square style={styles.paper} >
            <Typography  variant="h5" gutterBottom>
            </Typography>
            <List style={styles.list}>
            {messages.map(({ id, primary, secondary, person }) => (
                <Fragment key={id}>
                <ListItem button>
                    <ListItemText primary={primary} secondary={secondary} />
                </ListItem>
                </Fragment>
            ))}
            </List>
      </Paper>
        );
    }
}

export default rollHistory;

const styles = {
    root: {
      flexGrow: 1,
    },
    grow: {
      flexGrow: 1,
    },
    menuButton: {
      marginLeft: -12,
      marginRight: 20,
    },
    paper: {
        overflowY: 'scroll',
        
      },
    list: {
        maxHeight: 'calc(100vh - 185px)'
    }
  };